CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221205043736_InitialDbCreation', '10.0.11');

COMMIT;

START TRANSACTION;
CREATE TABLE "Ratings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Value" integer NOT NULL,
    "FileName" text NOT NULL,
    "Bucket" text NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Ratings_Bucket" ON "Ratings" ("Bucket");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221209094623_Ratings', '10.0.11');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_Ratings_Bucket";

ALTER TABLE "Ratings" DROP COLUMN "Bucket";

CREATE INDEX "IX_Ratings_FileName" ON "Ratings" ("FileName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230119030548_RemoveBucket', '10.0.11');

COMMIT;

START TRANSACTION;
DROP TABLE "Ratings";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230120053211_RemoveRating', '10.0.11');

COMMIT;

START TRANSACTION;
CREATE TABLE "Favourites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "UserName" text NOT NULL,
    CONSTRAINT "PK_Favourites" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Favourites_UserName" ON "Favourites" ("UserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230304143840_Favourites', '10.0.11');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_Favourites_UserName";

CREATE INDEX "IX_Favourites_Name" ON "Favourites" ("Name");

CREATE UNIQUE INDEX "IX_Favourites_UserName" ON "Favourites" ("UserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230305131019_Favourites-index', '10.0.11');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_Favourites_UserName";

CREATE INDEX "IX_Favourites_UserName" ON "Favourites" ("UserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230305133958_Favourites-index-update', '10.0.11');

COMMIT;

START TRANSACTION;
CREATE TABLE "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "FileName" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Tags_FileName" ON "Tags" ("FileName");

CREATE INDEX "IX_Tags_Name" ON "Tags" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230607051723_AddTags', '10.0.11');

COMMIT;

START TRANSACTION;
ALTER TABLE "Tags" ADD "Timestamp" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230616000359_AddTagTimeStamp', '10.0.11');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" TYPE character varying(128);

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" TYPE character varying(128);

ALTER TABLE "AspNetUsers" ALTER COLUMN "PhoneNumber" TYPE character varying(256);

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" TYPE character varying(128);

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" TYPE character varying(128);

CREATE TABLE "AspNetUserPasskeys" (
    "CredentialId" bytea NOT NULL,
    "UserId" text NOT NULL,
    "Data" jsonb NOT NULL,
    CONSTRAINT "PK_AspNetUserPasskeys" PRIMARY KEY ("CredentialId"),
    CONSTRAINT "FK_AspNetUserPasskeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserPasskeys_UserId" ON "AspNetUserPasskeys" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260825122114_AddPasskeys', '10.0.11');

COMMIT;

START TRANSACTION;
CREATE TABLE "ProcessingReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(32) NOT NULL,
    "Name" character varying(64) NOT NULL,
    "CreatedUtc" timestamp with time zone NOT NULL,
    "Html" text NOT NULL,
    CONSTRAINT "PK_ProcessingReports" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260903094756_AddProcessingReports', '10.0.11');

COMMIT;

