version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: arkaine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: michalhosna/adminer
    restart: always
    environment:
       ADMINER_DB: arkaine
       ADMINER_DRIVER: pgsql
       ADMINER_PASSWORD: password
       ADMINER_SERVER: postgres
       ADMINER_USERNAME: admin
       ADMINER_AUTOLOGIN: 1
       ADMINER_NAME: Arkaine Development Database

    ports:
      - 8080:8080
