<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server\Server.Arkaine.csproj" />
    <ProjectReference Include="..\Server.Arkaine.LocalB2\Server.Arkaine.LocalB2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Server\test.jpg" Link="test.jpg" CopyToOutputDirectory="Always" />
    <None Include="..\Server\test.mp4" Link="test.mp4" CopyToOutputDirectory="Always" />
    <None Include="..\Server\test.mp3" Link="test.mp3" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
