name: Publish Chrome Extension
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: Chrome.Arkaine/
          dest: chrome.arkaine.zip
      - uses: actions/upload-artifact@v1
        with:
          name: chrome.arkaine.zip
          path: ${{ github.workspace }}/chrome.arkaine.zip