name: Publish Chrome Extension
on:
  push:
    paths:
      - 'Chrome.Arkaine/update.xml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create CRX
        uses: actions/setup-node@v3
      - run: npm install crx -g
      - run: crx pack Chrome.Arkaine -o arkaine.crx
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "arkaine.crx"
          token: ${{ secrets.GITHUB_TOKEN }}
